Business.transaction do
Business.delete_all
Business.create!( :name => '1st America Home Medical Equipment', :address => "428 Northside Drive, Valdosta, GA 31602",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => '1st Franklin Financial Corporation', :address => "1900 Gornto Rd.  Ste. G-H, Valdosta, GA 31602",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => '306 North', :address => "310 N Patterson St, Valdosta, GA 31602",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Abigail H. Davis/Real Living Realty Advisors', :address => "1817 Green Circle, Valdosta, GA 31602",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Ameris Bank', :address => "3140 Inner Perimeter Rd., Valdosta, GA 31602",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Anchored Media Marketing', :address => "Blank, Blank, Blank Blank",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Animal Health Center', :address => "2905 Bemiss Road, Valdosta, GA 31602",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Astro Exterminating Services, Inc.', :address => "1708 Gornto Road, Valdosta, GA 31601",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Austins Cattle Co.', :address => "Blank, Blank, Blank Blank",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Azalea Health ', :address => "105 West Central Avenue, Valdosta, GA 31601",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Badcock Furniture and More', :address => "Blank, Blank, Blank Blank",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Barnes Health Care Services', :address => "200 S. Patterson St., Valdosta, GA 31601",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Batteries Plus Bulbs', :address => "1847 Norman Drive, Valdosta, GA 31601",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Big Nicks', :address => "904 Baytree Rd, Valdosta, GA 31602",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'BridgeBuilder Education & Investments', :address => "P.O. Box 2891, Valdosta, GA 31604",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Buffalo Wild Wings', :address => "1553 Baytree Road, Valdosta, GA 31602",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Bush Wealth Management ', :address => "2918 N. Oak St., Valdosta, GA 31602",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Ciao Bella SC Boutique, LLC', :address => "103 S. Patterson St. #A, Valdosta, GA 31601",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Citizens Community Bank', :address => "3261 N. Valdosta Rd, Valdosta, GA 31602",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'CJB Industries, Inc.', :address => "2114 Cypress Street, Valdosta, GA 31601",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Coldwell Banker Premier Real Estate', :address => "1108 Gornto Road, Valdosta, GA 31602",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Coldwell Banker Premier Real Estate', :address => "1108 Gornto Rd., Valdosta, GA 31602",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Coleman Talley LLP-William E. Holland', :address => "910 N Patterson Street, Valdosta, GA 31601",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Colony Bank ', :address => "3774 Old HWY 41 N., Valdosta, GA 31602",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Colquitt EMC', :address => "273 Norman Drive, Valdosta, GA 31601",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Commercial Banking Company', :address => "3462 North Valdosta Rd, Valdosta, GA 31602",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Commercial Banking Company', :address => "110 W. Main St., Hahira, GA 31632",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Commercial Banking Company', :address => "1215 Baytree Road, Valdosta, GA 31602",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Commercial Banking Company', :address => "635 Veterans Parkway W, Moultrie, GA 31788",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Commercial Banking Company-Tifton Branch', :address => "729 W 2nd Street, Tifton, GA 31794",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Commercial Real Estate Advisors - Andy Deal', :address => "1803A Green Circle, Valdosta, GA 31602",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Cooks Pest Control', :address => "823 Gil Harbin Ind Blvd, Valdosta, GA 31601",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Coombs Heating & Air Conditioning', :address => "307 West Lawson Street, Hahira, GA 31632",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Covingtons Dining & Catering', :address => "310 N. Patterson Street, Valdosta, GA 31601",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Cre8ive Zone', :address => "3320 Bemiss Road, Valdosta, GA 31605",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'C-Tech Water Solutions, LLC', :address => "99 Hamm Street, Valdosta, GA 31602",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Dairy Queen/The Lyoness Co.', :address => "3277 Inner Perimeter Rd., Valdosta, GA 30602",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Destiny Financial Services - A Family Heritage Life Provider', :address => "806 E. Jane St., Valdosta, GA 31601",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Direct Auto Insurance', :address => "1515 North Ashley Street, Valdosta, GA 31602",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Dumealz', :address => "3323 Bemiss Rd., Valdosta, GA 31605",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Edible Arrangements', :address => "1733 Gornto Road 104G, Valdosta, GA 31601",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'ELead1one', :address => "4001 Coleman Road N, Valdosta, GA 31602",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Embry-Riddle Aeronautical University', :address => "Moody Mail Service, Moody AFB, GA 31699",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Farmers Home Furniture Company', :address => "3135 N. Ashley Street, Valdosta, GA 31602",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Farmers Supply Company', :address => "1812 South Patterson Street, Valdosta, GA 31601",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'First Federal of Valdosta', :address => "411 N. Patterson Street, Valdosta, GA 31601",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'First State Bank & Trust Co.-North Ashley', :address => "510 N Ashley Street, Valdosta, GA 31601",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'First State Bank & Trust Company-ATM', :address => "2501 N Patterson Street, Valdosta, GA 31601",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'First State Bank & Trust Company-Baytree', :address => "1522 Baytree Road, Valdosta, GA 31601",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'First State Bank & Trust Company-Inner Perimeter', :address => "3650 Inner Perimeter Road, Valdosta, GA 31602",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'First State Bank & Trust Company-Lake Park', :address => "559 Lakes Blvd, Lake Park, GA 31636",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Fitmix Group Fitness and Personal Training', :address => "3323 Bemiss Rd., Valdosta, GA 31605",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Four Seasons Essential Oils, LLC', :address => "3716 Kingston Ct., Valdosta, GA 31605",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Fresh Beginnings, Inc.', :address => "4001 Coleman Road North, Valdosta, GA 31602",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Furniture Express/Beds For Less, Inc.', :address => "808 N. Patterson St., Valdosta, GA 31601",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Georgia Military College', :address => "4201 N Forrest Street, Valdosta, GA 31605",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Georgia Power Company', :address => "805 W Savannah Ave, Valdosta, GA 31601",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Goodwill Mission Services/Career Center', :address => "1000-E North Saint Augustine Road, Valdosta, GA 31601",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Hang Out Yoga, LLC', :address => "3308 Country Club Rd. Suite B, Valdosta, GA 31605",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Harvard Risk Management', :address => "Blank, Valdosta, GA 31602",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Heart Rize Fitness', :address => "1845 Norman Dr., Valdosta, GA 31601",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Highland Christian Academy', :address => "4023 Pine Grove Rd, Valdosta, GA 31605",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Holiday Inn Express & Suites', :address => "1330 N St Augustine Road, Valdosta, GA 31601",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'The Home Depot', :address => "1825 Norman Drive, Valdosta, GA 31601",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Hooters of Valdosta', :address => "1854 Clubhouse Dr, Valdosta, GA 31601",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Hug In A Mug Coffee', :address => "4165 Bemiss Rd., Valdosta, GA 31605",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Ink & Cotton', :address => "600 N. Patterson St., Valdosta, GA 31601",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Judy Martin Trexler/CR for Personal & Family Growth, LLC', :address => "2704 North Oak Street Bldg. L, Valdosta, GA 31602",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Kentucky Fried Chicken', :address => "1203 N. Ashley Street, Valdosta, GA 31601",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Kilby Family Dentistry', :address => "2704 North Oak St., Building C-1, Valdosta, GA 31602",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Langdale Vallotton LLP', :address => "1007 North Patterson St., Valdosta, GA 31601",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Law Office of Paul W. Hamilton, LLC', :address => "2918 N. Oak St., Valdosta, GA 31602",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Lemongrass Day Spa', :address => "3338 D Country Club Road, Valdosta, GA 31605",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Liberty National Life Insurance - Cannington Agency', :address => "401 Carswell Avenue Ste. 220, Waycross, GA 31501",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Literacy Volunteer Program of South Georgia, Inc.', :address => "221 S. Ashley Street, Valdosta, GA 31601",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Lowndes County Board of Commissioners', :address => "327 North Ashley Street 3rd Floor, Valdosta, GA 31601",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Lynne Brown/John Maxwell Team', :address => "2552 E US Highway 90, Madison, FL 32340",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Mediacom Residential', :address => "275 Norman Drive, Valdosta, GA 31601",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Mellow Mushroom', :address => "1526 Baytree Road, Valdosta, GA 31601",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Messiah Lutheran Church', :address => "500 Baytree Road, Valdosta, GA 31602",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Michelle Alden Counseling Services', :address => "3316 Bemiss Road, Valdosta, GA 31605",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Mink Chiropractic Center, LLC', :address => "409 Northside Drive, Valdosta, GA 31602",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Miss Kates Deep South Tours', :address => "Blank, Valdosta, GA 31605",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Music Funeral Services', :address => "3831 North Valdosta Road, Valdosta, GA 31602",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'New Hire Solutions, LLC', :address => "2904-E North Patterson Street, Valdosta, GA 31602",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'NG Telecom, Inc.', :address => "505 N. Toombs Street, Valdosta, GA 31601",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Northwind Apartment Homes', :address => "5148 Northwind Blvd., Valdosta, GA 31605",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Park University', :address => "3010 Robinson Road, Moody AFB, GA 31699",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Partners in Health Management LLC', :address => "202 West Gordon St. Suite A, Valdosta, GA 31601",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Pinwheels ', :address => "361 Northside Drive, Valdosta, GA 31602",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Powells Outdoor Power Equipment', :address => "2615 Bemiss Rd, Valdosta, GA 31602",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Prince Automotive of Valdosta, Inc.', :address => "4550 North Valdosta Road, Valdosta, GA 31602",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Ray Norton Tire & Auto Center', :address => "2606 Bemiss Road, Valdosta, GA 31602",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Real Living Realty Advisors-Ron Borders', :address => "1817 Green Cir., Valdosta, GA 31602",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Real Living Realty Advisors-Tammy Borders', :address => "1817 Green Cir., Valdosta, GA 31602",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Renasant Bank', :address => "3295 Inner Perimeter Road, Valdosta, GA 31602",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'RISE', :address => "129 N Patterson St, Valdosta, GA 31602",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Roto Rooter Plumbing & Drain Service', :address => "4307 North Valdosta Road, Valdosta, GA 31602",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'SAFT America Inc.', :address => "711 Gil Harbin Industrial Blvd., Valdosta, GA 31601",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Secure Records Solutions', :address => "105 Baybrook St., Thomasville, GA 31792",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'SJ Services inc DBA Stanley Steemer', :address => "1547 M E Thompson Dr., Valdosta, GA 31601",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Sleep Number by Select Comfort', :address => "1701 Norman Drive, Valdosta, GA 31601",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'South Georgia Eye Partners', :address => "4120 North Valdosta Rd., Valdosta, GA 31602",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'South Georgia Medical Center/SGMC', :address => "2501 N Patterson Street, Valdosta, GA 31602",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'South Georgia Travel', :address => "1300 Baytree Road, Valdosta, GA 31602",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'South Georgia Vein Centers', :address => "3338- L1 Country Club Road, Valdosta, GA 31605",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Southeastern Credit Union', :address => "P.O. Box 2067, Valdosta, GA 31604",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Southern Flooring of Valdosta & Kimblewood Blinds', :address => "808 N. Patterson St., Valdosta, GA 31601",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Southern Vein & Laser Center', :address => "3321-B North Valdosta Road, Valdosta, GA 31602",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Southwest Georgia Bank', :address => "3500 N. Valdosta Rd, Valdosta, GA 31602",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Spyderserve Corp', :address => "1711 Williams Street, Valdosta, GA 31602",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Steeda Autosports', :address => "2019 Steeda Way, Valdosta, GA 31601",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Talk 92.1', :address => "Blank, Blank, Blank Blank",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Tanner Investment Group', :address => "119 N Patterson St., Valdosta, GA 31601",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Team-Britt Mobile Game Arcade', :address => "3385 Fred Walker Rd., Valdosta, GA 31605",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Teamtemps Personnel Staffing, Inc.', :address => "1601 Baytree Road, Valdosta, GA 31602",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Thacker Dermatology, LLC', :address => "4233 Camelot Crossing, Valdosta, GA 31602",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'The Fields North Valdosta', :address => "480 Murray Rd., Valdosta, GA 31602",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'The Gardens', :address => "3531 Club Villas Drive, Valdosta, GA 31602",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Troy University Albany Area Support Center', :address => "1579 US HWY 19 S, Leesburg, GA 31763",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Turners Fine Furniture', :address => "3385 North Valdosta Road, Valdosta, GA 31602",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Valdosta Chiropractic & Rehab', :address => "220 Gornto Rd., Valdosta, GA 31602",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Valdosta City-Manager', :address => "P.O. Box 1125, Valdosta, GA 31603",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Valdosta City-Mayor', :address => "216 E Central Avenue, Valdosta, GA 31601",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Valdosta City Schools', :address => "1204 Williams St., Valdosta, GA 31601",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Valdosta Coca-Cola Bottling Company', :address => "2296 Highway 84 West, Valdosta, GA 31602",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Valdosta Nissan Cadillac', :address => "3685 Inner Perimeter Road, Valdosta, GA 31602",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Valdosta Insurance Services, Inc.', :address => "812 Northwood Dr., Valdosta, GA 31602",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Valdosta Oral & Maxillofacial Surgeons', :address => "2720 N. Oak Street, Valdosta, GA 31602",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Valdosta State University', :address => "1500 N. Patterson Street, Valdosta, GA 31698",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Valdosta-Lowndes Co. Conference Center & Tourism Authority', :address => "1 Meeting Place, Valdosta, GA 31601",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'ValdostaSOLD Real Estate Services', :address => "3314 Bemiss Road, Valdosta, GA 31605",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Velas Studio', :address => "Blank, Valdosta, GA 31601",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'WAAC FM', :address => "2973 Hwy 84 West, Valdosta, GA 31601",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'W P Walkers Vack, Inc.', :address => "4901 Lori St, Valdosta, GA 31605",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Watsons Pools & Patios, Inc.', :address => "210 N. Davis Street, Nashville, GA 31639",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Wild Adventures Theme Park', :address => "3766 Old Clyattville Road, Valdosta, GA 31601",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'WilTeck, LLC', :address => "5015 Inner Perimeter Rd., Valdosta, GA 31601",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Winnersville Fitness', :address => "1711 Norman Dr., Valdosta, GA 31601",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Wiregrass Georgia Technical College', :address => "4089 Val Tech Road, Valdosta, GA 31602",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Wiregrass Investment Management, LLC', :address => "3321 North Valdosta Rd, Valdosta, GA 31602",  logo_url: open('app/assets/images/placeholder.png'))
Business.create!( :name => 'Worthington Family Dentistry', :address => "3362 Greystone Way, Valdosta, GA 31605",  logo_url: open('app/assets/images/placeholder.png'))
#Business.create!( :name => 'Cr8ive Zone', :address => "3320 Bemiss Rd, Valdosta, GA 31605", logo_url: open('app/assets/images/cr8ivezone.png'))
#Business.create!( :name => 'Ray Norton Tire & Auto Center', :address => "2606 Bemiss Rd, Valdosta, GA 31602", logo_url: open('app/assets/images/raynorton.png'))
#Business.create!( :name => '1st America Home Medical Equipment', :address => "212 Northside Dr, Valdosta, GA 31602",  logo_url: open('app/assets/images/1stamericanhome.png'))
#Business.create!( :name => '1st Franklin Financial Corporation', :address => "1900 Gornto Rd Suite G, Valdosta, GA 31602",  logo_url: open('app/assets/images/1stfranklin.png'))
#Business.create!( :name => '306 North', :address => "306 N Patterson St, Valdosta, GA 31601",  logo_url: open('app/assets/images/306north.jpeg'))
end