Chamber.transaction do
Chamber.delete_all
Chamber.create!( :address => "3320 Bemiss Rd, Valdosta, GA 31604")
Chamber.create!( :address => "3320 Bemiss Rd, Valdosta, GA 31605")
end

Military.transaction do
Military.delete_all
Military.create!( :name => 'Doug Brown', :address => "1900 Gornto Rd Suite G, Valdosta, GA 31602")
Military.create!( :name => 'Stacy Herrington', :address => "306 N Patterson St, Valdosta, GA 31601")
end


Account.transaction do
Account.delete_all
Account.create!( :email => 'mandy@1stamericadrugs.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("1st America Home Medical Equipment"))
Account.create!( :email => 'cdb4586@1ffc.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("1st Franklin Financial Corporation"))
Account.create!( :email => 'Blank0@email.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("306 North"))
Account.create!( :email => 'abigail.davis.abr@gmail.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Abigail H. Davis/Real Living Realty Advisors"))
Account.create!( :email => 'michael.lee@amerisbank.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Ameris Bank"))
Account.create!( :email => 'anchoredmediamarketing@gmail.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Anchored Media Marketing"))
Account.create!( :email => 'rebecca@caringtogether.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Animal Health Center"))
Account.create!( :email => 'astro2@bellsouth.net', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Astro Exterminating Services, Inc."))
Account.create!( :email => 'hchamber@bellsouth.net', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Austins Cattle Co."))
Account.create!( :email => 'info@azaleahealth.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Azalea Health "))
Account.create!( :email => 'Blank1@email.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Badcock Furniture and More"))
Account.create!( :email => 'charlie@barneshc.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Barnes Health Care Services"))
Account.create!( :email => 'andy@4thwardgroup.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Batteries Plus Bulbs"))
Account.create!( :email => 'bignicksonbaytree@gmail.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Big Nicks"))
Account.create!( :email => 'admin@iamabridgebuilder.us', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("BridgeBuilder Education & Investments"))
Account.create!( :email => '246@buffalowildwings.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Buffalo Wild Wings"))
Account.create!( :email => 'stacy.bush@lpl.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Bush Wealth Management "))
Account.create!( :email => 'ciao_bellaboutique@outlook.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Ciao Bella SC Boutique, LLC"))
Account.create!( :email => 'tjones@citizenscommunitybank.net', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Citizens Community Bank"))
Account.create!( :email => 'cbeeland@cjbindustries.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("CJB Industries, Inc."))
Account.create!( :email => 'debbiehowell@valdostarealtors.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Coldwell Banker Premier Real Estate"))
Account.create!( :email => 'maryhstraka@gmail.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Coldwell Banker Premier Real Estate"))
Account.create!( :email => 'bill.holland@colemantalley.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Coleman Talley LLP-William E. Holland"))
Account.create!( :email => 'esmith@colonybank.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Colony Bank "))
Account.create!( :email => 'DixieLightfoot@colquittemc.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Colquitt EMC"))
Account.create!( :email => 'drussell@cbcbank.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Commercial Banking Company"))
Account.create!( :email => 'vgodwin@cbcbank.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Commercial Banking Company"))
Account.create!( :email => 'swarren@cbcbank.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Commercial Banking Company"))
Account.create!( :email => 'rkelly@cbcbank.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Commercial Banking Company"))
Account.create!( :email => 'Blank2@email.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Commercial Banking Company-Tifton Branch"))
Account.create!( :email => 'deal.andy47@gmail.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Commercial Real Estate Advisors - Andy Deal"))
Account.create!( :email => 'david.parrott@cookspest.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Cooks Pest Control"))
Account.create!( :email => 'coombs.hvac@yahoo.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Coombs Heating & Air Conditioning"))
Account.create!( :email => 'caterinc@bellsouth.net', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Covingtons Dining & Catering"))
Account.create!( :email => 'eomiteru2@yahoo.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Cre8ive Zone"))
Account.create!( :email => 'ctechwater@gmail.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("C-Tech Water Solutions, LLC"))
Account.create!( :email => 'atlas@lyonmgt.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Dairy Queen/The Lyoness Co."))
Account.create!( :email => 'brogers@legacyservices.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Destiny Financial Services - A Family Heritage Life Provider"))
Account.create!( :email => 'cynthia.hartwig@directgeneral.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Direct Auto Insurance"))
Account.create!( :email => 'info@dumealz.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Dumealz"))
Account.create!( :email => 'rmiller@gmail.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Edible Arrangements"))
Account.create!( :email => 'Blank3@email.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("ELead1one"))
Account.create!( :email => 'moody@erau.edu', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Embry-Riddle Aeronautical University"))
Account.create!( :email => 'tcarroll@valdostacity.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Farmers Home Furniture Company"))
Account.create!( :email => 'farmerssupplyco@bellsouth.net', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Farmers Supply Company"))
Account.create!( :email => 'leslie.vankirk@1stfederalvaldosta.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("First Federal of Valdosta"))
Account.create!( :email => 'Blank4@email.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("First State Bank & Trust Co.-North Ashley"))
Account.create!( :email => 'christinagodwin@fsbtc.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("First State Bank & Trust Company-ATM"))
Account.create!( :email => 'tammygoodin@fsbtc.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("First State Bank & Trust Company-Baytree"))
Account.create!( :email => 'billcowart@fsbtc.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("First State Bank & Trust Company-Inner Perimeter"))
Account.create!( :email => 'info@fsbtc.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("First State Bank & Trust Company-Lake Park"))
Account.create!( :email => 'morethanfit@gmail.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Fitmix Group Fitness and Personal Training"))
Account.create!( :email => 'mary.h.clement@gmail.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Four Seasons Essential Oils, LLC"))
Account.create!( :email => 'chip@freshbeginnings.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Fresh Beginnings, Inc."))
Account.create!( :email => 'cvannamee@msn.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Furniture Express/Beds For Less, Inc."))
Account.create!( :email => 'lhafer@gmc.edu', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Georgia Military College"))
Account.create!( :email => 'audking@southernco.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Georgia Power Company"))
Account.create!( :email => 'khamilton@gwisr.org', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Goodwill Mission Services/Career Center"))
Account.create!( :email => 'erika@hangoutyoga.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Hang Out Yoga, LLC"))
Account.create!( :email => 'jasmine.miles@harvardbenefits.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Harvard Risk Management"))
Account.create!( :email => 'mikell@heartrizefitness.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Heart Rize Fitness"))
Account.create!( :email => 'principal@hcavaldosta.org', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Highland Christian Academy"))
Account.create!( :email => 'ty@hiexvaldosta.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Holiday Inn Express & Suites"))
Account.create!( :email => 'Peter_A_Layne@homedepot.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("The Home Depot"))
Account.create!( :email => 'valdosta@hooters.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Hooters of Valdosta"))
Account.create!( :email => 'pms_ptac@yahoo.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Hug In A Mug Coffee"))
Account.create!( :email => 'hello@inkandcottongoods.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Ink & Cotton"))
Account.create!( :email => 'judytrex@bellsouth.net', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Judy Martin Trexler/CR for Personal & Family Growth, LLC"))
Account.create!( :email => 'kfc113@bellsouth.net', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Kentucky Fried Chicken"))
Account.create!( :email => 'dkilbymcg@gmail.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Kilby Family Dentistry"))
Account.create!( :email => 'shall@langdalelaw.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Langdale Vallotton LLP"))
Account.create!( :email => 'paul@paulwhamilton.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Law Office of Paul W. Hamilton, LLC"))
Account.create!( :email => 'michellealamb@gmail.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Lemongrass Day Spa"))
Account.create!( :email => 'br040@libnat.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Liberty National Life Insurance - Cannington Agency"))
Account.create!( :email => 'lvpinvaldosta@gmail.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Literacy Volunteer Program of South Georgia, Inc."))
Account.create!( :email => 'pdukes@lowndescounty.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Lowndes County Board of Commissioners"))
Account.create!( :email => 'Lynne@Lynnebrown.net', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Lynne Brown/John Maxwell Team"))
Account.create!( :email => 'dchaney@mediacomcc.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Mediacom Residential"))

Account.create!( :email => 'valdosta@coastalmellow.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Mellow Mushroom"))
Account.create!( :email => 'Office@MessiahLutheranVLD.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Messiah Lutheran Church"))
Account.create!( :email => 'michellealden22@gmail.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Michelle Alden Counseling Services"))
Account.create!( :email => 'manager@minkchiro.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Mink Chiropractic Center, LLC"))
Account.create!( :email => 'kate@misskatestours.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Miss Kates Deep South Tours"))
Account.create!( :email => 'casey@musicfuneralservices.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Music Funeral Services"))
Account.create!( :email => 'sandy@NewHireSolutions.net', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("New Hire Solutions, LLC"))
Account.create!( :email => 'srice@e-c-group.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("NG Telecom, Inc."))
Account.create!( :email => 'northwindapts@hotmail.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Northwind Apartment Homes"))
Account.create!( :email => 'juanita.walker@park.edu', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Park University"))
Account.create!( :email => 'jlmcghin@att.net', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Partners in Health Management LLC"))
Account.create!( :email => 'pinwheelsquilts@gmail.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Pinwheels "))
Account.create!( :email => 'helenpowell09@yahoo.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Powells Outdoor Power Equipment"))
Account.create!( :email => 'jay@princeauto.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Prince Automotive of Valdosta, Inc."))
Account.create!( :email => 'rntac@bellsouth.net', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Ray Norton Tire & Auto Center"))
Account.create!( :email => 'ron@ronborders.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Real Living Realty Advisors-Ron Borders"))
Account.create!( :email => 'tammy@ronborders.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Real Living Realty Advisors-Tammy Borders"))
Account.create!( :email => 'will.kemp@renasant.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Renasant Bank"))
Account.create!( :email => 'ghunter@risere.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("RISE"))
Account.create!( :email => 'garotorooter@bellsouth.net', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Roto Rooter Plumbing & Drain Service"))
Account.create!( :email => 'terry.cooper@saftbatteries.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("SAFT America Inc."))
Account.create!( :email => 'christopher@securerecordssolutions.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Secure Records Solutions"))
Account.create!( :email => 'steve.adkins@steemer.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("SJ Services inc DBA Stanley Steemer"))
Account.create!( :email => 'SleepNumberValdosta@SleepNumber.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Sleep Number by Select Comfort"))
Account.create!( :email => 'chanson@southgeorgiaeye.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("South Georgia Eye Partners"))
Account.create!( :email => 'johnny.ball@sgmc.org', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("South Georgia Medical Center/SGMC"))
Account.create!( :email => 'jane@sgatravel.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("South Georgia Travel"))
Account.create!( :email => 'sgvcthowell@bellsouth.net', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("South Georgia Vein Centers"))
Account.create!( :email => 'mgudely@southeasterncu.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Southeastern Credit Union"))
Account.create!( :email => 'calvinstubbs@stcvaldosta.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Southern Flooring of Valdosta & Kimblewood Blinds"))
Account.create!( :email => 'Blank5@email.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Southern Vein & Laser Center"))
Account.create!( :email => 'jeff.hanson@sgfc.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Southwest Georgia Bank"))
Account.create!( :email => 'gary@spyderserve.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Spyderserve Corp"))

Account.create!( :email => 'dario@steeda.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Steeda Autosports"))
Account.create!( :email => 'Blank6@email.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Talk 92.1"))
Account.create!( :email => 'john@tannerinvestmentgroup.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Tanner Investment Group"))
Account.create!( :email => 'teambritt28@gmail.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Team-Britt Mobile Game Arcade"))
Account.create!( :email => 'gpanizzi@teamtemps.net', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Teamtemps Personnel Staffing, Inc."))
Account.create!( :email => 'brandi.thackerderm@gmail.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Thacker Dermatology, LLC"))
Account.create!( :email => 'valdostaasstmanager@thefieldsliving.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("The Fields North Valdosta"))
Account.create!( :email => 'thegardens@invmgt.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("The Gardens"))
Account.create!( :email => 'cobbj@troy.edu', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Troy University Albany Area Support Center"))
Account.create!( :email => 'jerry@turnerfurniture.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Turners Fine Furniture"))
Account.create!( :email => 'lacie_guy@yahoo.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Valdosta Chiropractic & Rehab"))
Account.create!( :email => 'mbarber@valdostacity.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Valdosta City-Manager"))
Account.create!( :email => 'jgayle@valdostacity.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Valdosta City-Mayor"))
Account.create!( :email => 'tcason@gocats.org', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Valdosta City Schools"))

Account.create!( :email => 'matthallman@ccbcu.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Valdosta Coca-Cola Bottling Company"))
Account.create!( :email => 'tko@thetkogroup.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Valdosta Nissan Cadillac"))
Account.create!( :email => 'mdorsey@valdostainsurance.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Valdosta Insurance Services, Inc."))
Account.create!( :email => 'johnroandds@valdostaoms.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Valdosta Oral & Maxillofacial Surgeons"))
Account.create!( :email => 'rcarvajal@valdosta.edu', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Valdosta State University"))
Account.create!( :email => 'chamilton@valdostatourism.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Valdosta-Lowndes Co. Conference Center & Tourism Authority"))
Account.create!( :email => 'valdostasold@gmail.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("ValdostaSOLD Real Estate Services"))
Account.create!( :email => 'info@velasstudio.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Velas Studio"))

Account.create!( :email => 'kells@riversradio.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("WAAC FM"))
Account.create!( :email => 'egri789@att.net', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("W P Walkers Vack, Inc."))
Account.create!( :email => 'watsonspoolsandpatios@windstream.net', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Watsons Pools & Patios, Inc."))
Account.create!( :email => 'mdeese@wildadventures.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Wild Adventures Theme Park"))

Account.create!( :email => 'susan@wilteck.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("WilTeck, LLC"))
Account.create!( :email => 'morethanfit2@gmail.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Winnersville Fitness"))
Account.create!( :email => 'customerservice@wiregrass.edu', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Wiregrass Georgia Technical College"))
Account.create!( :email => 'jimmy.shiver@lpl.com', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Wiregrass Investment Management, LLC"))
Account.create!( :email => 'amy.wfd@mediacombb.net', :password => 'changeme', :password_confirmation => 'changeme', :approved => true, :accountable => Business.find_by_name("Worthington Family Dentistry"))

Account.create!( :email => 'chamber1@email.com', :password => 'changeme', :approved => true, :password_confirmation => 'changeme',:accountable => Chamber.find_by_address("3320 Bemiss Rd, Valdosta, GA 31604"))
Account.create!( :email => 'chamber2@email.com', :password => 'changeme', :approved => true, :password_confirmation => 'changeme',:accountable => Chamber.find_by_address("3320 Bemiss Rd, Valdosta, GA 31605"))

Account.create!( :email => 'military1@email.com', :password => 'changeme', :approved => true, :password_confirmation => 'changeme',:accountable => Military.find_by_name("Doug Brown"))
Account.create!( :email => 'military2@email.com', :password => 'changeme', :approved => true, :password_confirmation => 'changeme',:accountable => Military.find_by_name("Stacy Herrington"))

end